[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "MesloLGM Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGM Nerd Font"
style = "Regular"

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window.padding]
x = 0
y = 0

[general]
import = [
    "~/.config/alacritty/themes/tachyon.toml"
]

[window]
startup_mode = "Fullscreen"
decorations = "None"
opacity = 1

[mouse]
hide_when_typing = true
